### DISCUSSION TITLE
How to hide the axis name

### DISCUSSION THREAD

**Discussion by joehei** [GSI-CS-CO/chart-fx#637] [Q&A] [answered]
Hi all,
I have a time x-axis, for which i would like to hide the name and unit label. In that case it is obvious what it is and I would like to save the space. I tried to hide it via CSS but had no luck.
Many thanks

**Comment by joehei** [comment]
I tried this:

```
.axis .axis-tick-label {
  visibility: visible;
  -fx-font-family: "System";
  -fx-font-size:9;
}

.axis .axis-label {
  visibility: hidden;
}
```
but this hides all labels not just the one for the x-axis

**Reply by ennerf** [reply, marked as answer]
You can add another CSS class to the axis, e.g.,

```Java
DefaultNumericAxis xAxis = ...;
xAxis.getStyleClass().add("reduced-x-axis")
```
```css
.reduced-x-axis .axis-tick-label {
  visibility: visible;
  -fx-font-family: "System";
  -fx-font-size:9;
}

.reduced-x-axis .axis-label {
  visibility: hidden;
}
```
